Repository reactphp/cache, pull requests merged in 2018-03, with the labels that each got.

#23 Return Promise for set and remove
  README.md
  src/ArrayCache.php
  src/CacheInterface.php
  tests/ArrayCacheTest.php
Labels: BC break, maintenance, new feature

#26 Simple LRU implementation for ArrayCache
  README.md
  src/ArrayCache.php
  tests/ArrayCacheTest.php
  tests/TestCase.php
Labels: new feature

#27 Add $default to return instead of null on cache miss for get()
  README.md
  src/ArrayCache.php
  src/CacheInterface.php
  tests/ArrayCacheTest.php
Labels: easy pick, new feature
